name: Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate AL Code
        uses: joneug/mdal-action@v1
        with:
          model-file: src/seminar-management.mdal
