name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate AL Code
        uses: joneug/mdal-action@master
        with:
          model-file: src/seminar-management.mdal
