name: Release

on:
    push:
      tags:
        - 'v*.*.*'

jobs:
  build:
    defaults:
      run:
        shell: powershell
    env:
      IMAGE_NAME: mcr.microsoft.com/businesscentral/sandbox:ltsc2019
      TEST_USERNAME: docker
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      CONTAINER_NAME: tmp
      APP_NAME: seminar-management.app
    runs-on: windows-latest
    steps:
      - name: Set up NAV Container
        run: |
          Install-Module navcontainerhelper -Force
          Get-Command -Module navcontainerhelper | Out-Null
          New-NavContainer `
            -imageName $env:IMAGE_NAME `
            -containerName $env:CONTAINER_NAME `
            -accept_eula `
            -accept_outdated `
            -auth NavUserPassword `
            -credential (New-Object PSCredential $env:TEST_USERNAME, (ConvertTo-SecureString $env:TEST_PASSWORD -AsPlainText -Force)) `
            -additionalParameters @('--volume ' + '"' + (Join-Path $pwd ":c:\share") + '"')
      - uses: actions/checkout@v2
      - name: Generate AL Code
        uses: joneug/mdal-action@v1
        with:
          model-file: src/seminar-management.mdal
      - name: Build App
        run: |
          Compile-AppInBCContainer `
            -containerName $env:CONTAINER_NAME `
            -credential (New-Object PSCredential $env:TEST_USERNAME, (ConvertTo-SecureString $env:TEST_PASSWORD -AsPlainText -Force)) `
            -appProjectFolder $pwd `
            -appOutputFolder $pwd `
            -appName $env:APP_NAME
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}
          asset_name: ${{ env.APP_NAME }}
          asset_content_type: application/zip
